### ISSUE TITLE
Argument "src" has already been defined, thus it should not be defined again.

### ISSUE THREAD

**Issue by tobiasschaeferptb** [velletti/ke_questionnaire#1]
Hello,

for some reason I get this error message in the Frontend
Argument "src" has already been defined, thus it should not be defined again."
when I try to use the KE Questionnaire plugin.
The full error message from the TYPO3 log is:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1253036401: Argument "src" has already been defined, thus it should not be defined again. | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file /srv/www/libs/typo3_src-8.7.24/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 168.

When I comment out the exception in the function registerArgument it works
```
    protected function registerArgument($name, $type, $description, $required = false, $defaultValue = null)
    {
        if (array_key_exists($name, $this->argumentDefinitions)) {
            /*throw new Exception(
                'Argument "' . $name . '" has already been defined, thus it should not be defined again.',
                1253036401
            );*/
        }
        $this->argumentDefinitions[$name] = new ArgumentDefinition($name, $type, $description, $required, $defaultValue);
        return $this;
    }

```
Any ideas why this happens?

Greatings

Tobias

**Comment by velletti** [comment]
It looks as if you are using a type of question that requieres a Viewhelper i did not fix. 

i had 30 ke_questionaires made with V6 LTS and they should run in V8 .. 

to find the error: disable all questions used in that ke_questionaire plugin. Find which element makes the error. 

Tell me, which Question type it is maybe i can find the time to fix also that viewhelper

**Comment by tobiasschaeferptb** [comment]
The error occurs as soon as I include a question, with or even without an answer. For me it looks like the problem is caused by the image field within a question. But it also occurs if there isn't any image set in the question element. Here's the full stack trace as a PDF [https://www.ptb.de/cms/fileadmin/user_upload/TYPO3_Exception_KE_Questionnaire.pdf](https://www.ptb.de/cms/fileadmin/user_upload/TYPO3_Exception_KE_Questionnaire.pdf)

**Comment by velletti** [comment]
I had setup yesterday a new dev instance for this with enough data
 yes i can reproduce it:

the ke Image viewhelper does not work . 

You have 2 Posabilities: 
overwrite the partial
/Private/Partials/Question/QuestionImage.html
and replace the 
			<ke:image src="uploads/tx_kequestionnaire/{question.image}" alt="{question.image}" width="{settings.question.image.top.width}" height="{settings.question.image.top.height}" minWidth="{settings.question.image.top.minWidth}" minHeight="{settings.question.image.top.minHeight}" maxWidth="{settings.question.image.top.maxWidth}" maxHeight="{settings.question.image.top.maxHeight}" />

with a default fluid image viewhelper in your partial 


or wait until this weekend .. i will fix it

**Comment by tobiasschaeferptb** [comment]
The error occurs as soon as I include a question, with or even without an answer. For me it looks like the problem is caused by the image field within a question. But it also occurs if there isn't any image set in the question element. Here's the full stack trace as a PDF [https://www.ptb.de/cms/fileadmin/user_upload/TYPO3_Exception_KE_Questionnaire.pdf](https://www.ptb.de/cms/fileadmin/user_upload/TYPO3_Exception_KE_Questionnaire.pdf)

**Comment by tobiasschaeferptb** [comment]
As you suggested in your email it is enough to replace ke:image with f:image in the partial Resources/Private/Partials/Question/QuestionImage.html:
`{namespace ke=Kennziffer\KeQuestionnaire\ViewHelpers}
<f:if condition="{question.image}">
	<div class="keqImage keqImage{position}">
		<f:if condition="{0: question.imagePosition} == {0: 'top'}">
			<f:image src="uploads/tx_kequestionnaire/{question.image}" alt="{question.image}" width="{settings.question.image.top.width}" height="{settings.question.image.top.height}" minWidth="{settings.question.image.top.minWidth}" minHeight="{settings.question.image.top.minHeight}" maxWidth="{settings.question.image.top.maxWidth}" maxHeight="{settings.question.image.top.maxHeight}" />
		</f:if>
		<f:if condition="{0: question.imagePosition} == {0: 'right'}">
			<f:image src="uploads/tx_kequestionnaire/{question.image}" alt="{question.image}" width="{settings.question.image.right.width}" height="{settings.question.image.right.height}" minWidth="{settings.question.image.right.minWidth}" minHeight="{settings.question.image.right.minHeight}" maxWidth="{settings.question.image.right.maxWidth}" maxHeight="{settings.question.image.right.maxHeight}" />
		</f:if>
		<f:if condition="{0: question.imagePosition} == {0: 'left'}">
			<f:image src="uploads/tx_kequestionnaire/{question.image}" alt="{question.image}" width="{settings.question.image.left.width}" height="{settings.question.image.left.height}" minWidth="{settings.question.image.left.minWidth}" minHeight="{settings.question.image.left.minHeight}" maxWidth="{settings.question.image.left.maxWidth}" maxHeight="{settings.question.image.left.maxHeight}" />
		</f:if>
		<f:if condition="{0: question.imagePosition} == {0: 'bottom'}">
			<f:image src="uploads/tx_kequestionnaire/{question.image}" alt="{question.image}" width="{settings.question.image.bottom.width}" height="{settings.question.image.bottom.height}" minWidth="{settings.question.image.bottom.minWidth}" minHeight="{settings.question.image.bottom.minHeight}" maxWidth="{settings.question.image.bottom.maxWidth}" maxHeight="{settings.question.image.bottom.maxHeight}" />
		</f:if>
	</div>
</f:if>`

**Comment by velletti** [comment]
should fixed 👍 i remove ke:image in all default tempaltes/ partials and replaced it with f:image
and additionally made the ke:image Viewhelper identically to the default fluid 

https://github.com/velletti/ke_questionnaire/commit/f5b0d1b18e7ca763c8951b8639db00f20ad700df
