### ISSUE TITLE
The argument answer was registered with type MatrixRow, but is of type MatrixHeader

### ISSUE THREAD

**Issue by tobiasschaeferptb** [velletti/ke_questionnaire#2]
If I use the answer type Matrix header it leads to this exception:
The argument "answer" was registered with type "Kennziffer\KeQuestionnaire\Domain\Model\AnswerType\MatrixRow", but is of type "Kennziffer\KeQuestionnaire\Domain\Model\AnswerType\MatrixHeader"

**Comment by velletti** [comment]
I do not have a working example in V 6.x using matrix or matrix header (l used this type last time 6 Years Ago and forgot how i worked then) 
the viewhelper itself looks strange to me as it is used in the partial martixRow and matrixHeader with the same argument 'answer' that will explain the error message. But inside of the renderFunction the agrument type matrixrow is not renderd: only matrixHeader and extendedMatrixHeader

But maybe cahngeing the viewhelper:
www/http/typo3conf/ext/ke_questionnaire/Classes/ViewHelpers/MatrixRowViewHelper.php

with the code below helps .. if yes, i can check it in .. 


`<?php
namespace Kennziffer\KeQuestionnaire\ViewHelpers;
/***************************************************************
 *  Copyright notice
 *
 *  (c) 2013 Kennziffer.com <info@kennziffer.com>, www.kennziffer.com
 *
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 *
 *
 * @package ke_questionnaire
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
 *
 */
class MatrixRowViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper {

    /**
     * @var boolean
     */
    protected $escapeChildren = false;

    /**
     * @var boolean
     */
    protected $escapeOutput = false;


    /**
     * Initialize arguments.
     */
    public function initializeArguments()
    {
        parent::initializeArguments();
        $this->registerArgument('answer', '\Kennziffer\KeQuestionnaire\Domain\Model\AnswerType\MatrixRow|\Kennziffer\KeQuestionnaire\Domain\Model\AnswerType\MatrixHeader|\Kennziffer\KeQuestionnaire\Domain\Model\AnswerType\ExtendedMatrixHeader', 'Answer Type Matrix or Matrix Header');
        $this->registerArgument('question', '\Kennziffer\KeQuestionnaire\Domain\Model\QuestionType\Question', 'question');
        $this->registerArgument('as', 'string', 'The name of the iteration variable');
    }

	/**
	 * @return string
	 */
	public function render( ) {
        $answer = $this->arguments['answer'] ;
        $question = $this->arguments['question'] ;
        $as = $this->arguments['as'] ;

		if (get_class($answer) == 'Kennziffer\\KeQuestionnaire\\Domain\\Model\\AnswerType\\MatrixHeader' OR get_class($answer) == 'Kennziffer\\KeQuestionnairePremium\\Domain\\Model\\AnswerType\\ExtendedMatrixHeader'){
		    $rows = $answer->getRows($question);
			
            $templateVariableContainer = $this->renderingContext->getVariableProvider();
            if ($question === NULL) {
                return '';
            }
            $output = '' ;
            foreach ($rows as $nr => $element){
                $templateVariableContainer->add($as, $element);
                $output .= $this->renderChildren();
                $templateVariableContainer->remove($as);
            }            
        }
        return $output;
	}	
}`

**Comment by velletti** [comment]
okay, found it: the type should be 'mixed' 

see latest version
