### ISSUE TITLE
No values for checkbox and radiobuttons in csv export

### ISSUE THREAD

**Issue by tobiasschaeferptb** [velletti/ke_questionnaire#3]
Hello Jörg,

if there is a checkbox or a radiobutton included in a KeQ content element and if the frontend user checks this checkbox or radiobutton it doesn't lead to a value in the csv export. So it isn't possible to figure out if a checkbox or radiobutton was checked or not.

Greetings
Tobias

**Comment by velletti** [comment]
Hi thobias. As i have many working surveys using checkboxes, it could be a java script problem, as the  ke extension uses Javascript to change the value of the key element for ☒. Can you recheck if you included the Javascript or there are any errors 🤔

**Comment by tobiasschaeferptb** [comment]
Hi Jörg,

I wasn't aware that KeQ comes with its own jQuery und jQueryUi files. Since the website also includes both files through page.includeJSFooterlibs I deactivated this include. But the solution for my problem was something else:
the field "Marker for RadioButton and CheckBoxes answers" in the export module.
Once you set a marker here it is used in the exported csv file.

Greetings
Tobias
